version: '3.9'

services:
  user-service:
    build: 
      context: ./user-service
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    environment:
      env_file: "./user-service/.env"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      postgres:
        condition: service_healthy

  order-service:
    build: 
      context: ./order-service
      dockerfile: ./Dockerfile
    ports:
      - "8081:80"
    environment:
      env_file: "./order-service/.env"  
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - "27017:27017"
    environment:
      env_file: "./.env"
    volumes:
      - ./db-data/mongo:/data/db
  
  postgres:
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      env_file: "./.env"
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 5s
      timeout: 5s
      retries: 20

  migrate:
    image: migrate/migrate
    container_name: migrate
    volumes:
      - ./user-service/migrations:/database
    command:
      ["-path", "/database", "-database", "postgres://postgres:password@postgres:5432/users?sslmode=disable", "up"]
    depends_on:
      postgres:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./db-data/rabbitmq/:/var/lib/rabbitmq/