version: '3.9'

services:
  user-service:
    build: 
      context: ./user-service
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    environment:
      PORT: ':80'
      PG_DSN: 'postgres://postgres:password@postgres:5432/users?sslmode=disable'
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      GRPC_PORT: '50001'
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      postgres:
        condition: service_healthy

  order-service:
    build: 
      context: ./order-service
      dockerfile: ./Dockerfile
    ports:
      - "8081:80"
    environment:
      PORT: ':80'
      MONGO_URL: mongodb://mongo:27017
      MONGO_USERNAME: mongo
      MONGO_PASSWORD: password
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      GRPC_URL: user-service:50001
  
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  mongo:
    image: 'mongo:4.2.16-bionic'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: orders
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./db-data/mongo:/data/db
  
  postgres:
    image: 'postgres:14.0'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 5s
      timeout: 5s
      retries: 20

  migrate:
    image: migrate/migrate
    container_name: migrate
    volumes:
      - ./user-service/migrations:/database
    command:
      ["-path", "/database", "-database", "postgres://postgres:password@postgres:5432/users?sslmode=disable", "up"]
    depends_on:
      postgres:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./db-data/rabbitmq/:/var/lib/rabbitmq/